import Head from "next/head";
import Image from "next/image";
import Calorie from "../components/Calorie";
import CardFood from "../components/CardFood";
import Foodlist from "../components/Foodlist";
import Footer from "../components/Footer";
import Landing from "../components/Landing";
import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>stayHealthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo 1.png" />
      </Head>

      <Navbar/> 
        <div className="max-w-7xl md:w-xl lg:w-5xl ">
          <Landing />
          <Calorie />
        <Foodlist />
        </div>
      <Footer/>
        
    </>
  );
}
